### ISSUE TITLE
SetCVar("nameplateMaxDistance", "6e1")  can set the nameplace visibility to 60 yards in Classic realms

### ISSUE THREAD

**Issue by SwimmingTiger** [Stanzilla/AdvancedInterfaceOptions#23] opened 2019-09-08 15:43 UTC
Use scientific notation to bypass Blizzard's 20-yard limit in Wow Classic realms. Although Blizzard may fix it in the future, this method is currently works. It can even be set to more than 100 yards.

I modified AdvancedInterfaceOptions in my own collection of addons so that my friends can set the cvar like this. They all like the feature, and everyone sets more than 20 yards (at least 30 yards).

Here is my committing. If you want, you are free to merge some or all of these codes into your repository.

https://github.com/SwimmingTiger/WowBigfootClassic/commit/afda2bac0b3eb127300ee235ed25eaa50cec2c07#diff-1654e03370ef8abdccb257cdfb67a2d5R235

**Comment by Stanzilla** [comment] 2019-09-08 16:30
This is already fixed in the next classic build so not worth adding

**Comment by semlar** [comment] 2019-09-08 22:13
We appreciate your contribution, but this is actually a bug in the client and will be patched out of the game soon.

As a general rule, if something is obviously not working as intended we would prefer not to integrate it into the addon only to have to remove it again after it's been fixed.

**Closed** 2019-09-08 22:46 UTC
